### ISSUE TITLE
Can you provide explanation hot to connect the LCD? which GPIOs?

### ISSUE THREAD

**Issue by Philusha1983** [breiti78/craftbeerpiLCD#16]
Can you provide explanation hot to connect the LCD? which GPIOs?

Thanks

**Comment by breiti78** [comment]
Vcc - 5V
GND - Ground
SDA - GPIO2
SCL - GPIO3

**Comment by Philusha1983** [comment]
Any special parts? or instalation?
or just connect it to pi and run the plugin?

*Philip* :)

**Comment by breiti78** [comment]
All you need is a i2c lcd display 1602 or 2004

**Comment by Philusha1983** [comment]
I have it - thanks!​

*Philip* :)

**Comment by Philusha1983** [comment]
Can anybody help me to understand why I don't see any number?
I'm trying to connect Rpi Zero W to LCD 2004a screen.
All the steps were done but no number when sending:

```
pi@raspberrypi:~ $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```


![image](https://user-images.githubusercontent.com/7344475/35609896-ed13d2ac-0667-11e8-8779-3a368422cb27.png)
