### ISSUE TITLE
feature suggestion : fermentation display

### ISSUE THREAD

**Issue by Philusha1983** [breiti78/craftbeerpiLCD#17]
feature suggestion: 

Maybe it's possible to show fermentation section when not brewing?

- fridge name
- brew name
- target temp
- sensor 1
- sensor 2
- sensor 3
- cooler\heater state (on/off)

if controlling more than one fridge to toggle between the fridges.

**Comment by breiti78** [comment]
Thanks for the suggestion. Fermentation is actually the reason why I am working on this plugin. 
Time is unfortunately very limited on my side at the moment. But I already started the development work for the fermentation part.

**Comment by JamFfm** [comment]
Actually I am working at a simple LCD Display for Fermentation. It will show fermenter name (same as fridge name?), target temp, sensor1. It should togle between the fermernters. I am struggeling to get the stepname. And time is missing.

**Comment by JamFfm** [comment]
simple fermenter view is implemented in the latest pullrequest. Please test it if you like

**Comment by JamFfm** [comment]
New release has got all features mentioned. Only sensor 2,3 is not shown. 
Therefore the remaining time of the step is shown.
