### ISSUE TITLE
Fermentation Screen Issue

### ISSUE THREAD

**Issue by ollinator2000** [breiti78/craftbeerpiLCD#23]
For some reason i can't get the fermentation screen working . Brew Kettle works perfect. 
I ve only one temperature sensor and Power Plug. But when i remove the kettle and setup a fermentation "thing" nothing appears on the screen . 
I added a target temperature and a step which contains 4 Degree Celsius for 99 days. 

am i doing something wrong ??

**Comment by JamFfm** [comment]
Tomorrow evening I got the chance to check if it is the same on my CBPI System. Did you put in 4.00 Degrees? What about if you still leave a Kettle in the brewing section. You don t Need to remove the kettle. Just put the sensor in the Fermentation kette too.

**Comment by JamFfm** [comment]
If you like to send the apps log or only the error lines this could help. 
Is there a heater and cooler defined? Just do that. I assume the code will throw an error if no heater and cooler is defined.

**Comment by ollinator2000** [comment]
I removed the kettle. I ll retest tomorrow by adding a heater ! I ll then check logs ..

**Comment by ollinator2000** [comment]
I did some more tests . Unfortunately without success. 8-( 
i readied a kettle , the display shows the kettle values perfectly. but not the fermenter .
fermenter_1.log

2018-02-05 09:17:27,4.0
2018-02-05 09:17:33,4.0
2018-02-05 09:17:39,4.0

**Comment by JamFfm** [comment]
Please send the app.log lines with error.

**Comment by JamFfm** [comment]
be shure you have defined a heater **and** cooler at the Fermenter. Using only a cooler will produse the error. I can see it in the app.log file. I try to fix the Code to avoid such a mistake. But I am a rookie using Python.

**Comment by JamFfm** [comment]
![fermenter](https://user-images.githubusercontent.com/24195024/35829831-7372c4e2-0ac4-11e8-9265-47ae717c6b69.JPG)

![ferment](https://user-images.githubusercontent.com/24195024/35829888-a57bd10e-0ac4-11e8-80ea-47ca5d87f94c.JPG)

LCD shows all values

**Comment by JamFfm** [comment]
OK fix is pulished. Ollinator2000 please just update the LCDDisplay Plugin. And please report what happend ;-)

**Comment by JamFfm** [comment]
do not Forget the reboot of CBPI3.

**Comment by ollinator2000** [comment]
I found the mistake . The fermentation doesn’t work if the there is no heater configured 😉 
I setup a dummy heater and now it works . THX for your help !!!
