### ISSUE TITLE
init method

### ISSUE THREAD

**Issue by tstrooba** [breiti78/craftbeerpiLCD#5]
Hi, 
I could nog get this working after installing from craftbeerpi UI.
I got an error "lcdjob() takes exactly 1 argument (0 given)".  I edited the __init__.py file and removed the "api" parameter.  Things started working then.

What am I doing wrong?

Thx,
Tim

**Comment by breiti78** [comment]
Hi Tim. Which cbpi version do you have?

**Comment by tstrooba** [comment]
I'm using version 3, just noticed there's another branch without the parameter in the init().  Should I use a different Craftbeerpi3 branch or the other LCD branch?

**Comment by tstrooba** [comment]
It would be nice if we could read the craftbeerpi version and display that, instead of a fixed string :)

**Comment by breiti78** [comment]
It should work with the latest cbpi master branch. I'm working on an update to have the parameters not hard coded anymore and to also read the version.

**Comment by tstrooba** [comment]
I just installed version 3 yesterday, so should be on the latest version.  And I can use the master branch of craftbeerpiLCD?  What else can I check?

**Comment by JamFfm** [comment]
This is a LCD Version where the version of CBPI is read from a file.
The kettlename and remaining time is now shown in the same line.
[__init__.py(v2.1).txt](https://github.com/breiti78/craftbeerpiLCD/files/1185587/__init__.py.v2.1.txt)

tstrooba have you tryed pull update. I would prefer to to this from the ./install.sh. In The System menue this should be the same.
If this still does not help, deleting of the database file helped for me (/home/pi/craftbeerpi3/craftbeerpi.db)
The database installs itself nothing to do but reboot.
Keep in mind you have to keyin all the kettle, sensors, etc. So store which gpio are used. 

Here systemmenue and please use the masterbrach not the stabel one.

![image](https://user-images.githubusercontent.com/24195024/28752423-22c257d2-751f-11e7-972f-3310d7073acf.png)
