### ISSUE TITLE
New Feature: Blinking beerglass to notice LCD still working in singelkettle mode

### ISSUE THREAD

**Issue by JamFfm** [breiti78/craftbeerpiLCD#7]
sorry tryed to edit the file and it updated the __init__.py in the RPLCD branch. Just wanted to suggest the "Feature" Tomorrow I can test it in a testsystem.

**Comment by cow77** [comment]
Works nice for me.

**Comment by JamFfm** [comment]
Thanks for reply. Works for me too. But:
I don't like the Bierglas blinking together with remaining time. I'm going to change that.
